#!/usr/bin/env bash
# configure a load balancer

sudo apt-get -y update
sudo apt-get -y install haproxy

sudo service haproxy start

echo 'frontend theproxy
        bind *:80
	default_backend my_backend_servers

backend my_backend_servers
	balance roundrobin
	server 497003-web-01 54.174.234.210:80
	server 497003-web-02 35.175.135.236:80' | sudo tee -a /etc/haproxy/haproxy.cfg

sudo service haproxy reload
